const path = require("path");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  webSidebar: [{type: 'autogenerated', dirName: 'web'}],
  backendSidebar: [{type: 'autogenerated', dirName: 'backend'}],
  nativeSidebar: [{type: 'autogenerated', dirName: 'native'}],
  whelkSidebar: [{type: 'autogenerated', dirName: 'whelk'}],
};

module.exports = sidebars;
