const path = require("path");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  backendSidebar: [{type: 'autogenerated', dirName: 'backend'}],
  webSidebar: [{type: 'autogenerated', dirName: 'web'}],
  nativeSidebar: [{type: 'autogenerated', dirName: 'native'}],
  aiSidebar: [{type: 'autogenerated', dirName: 'ai'}],
  whelkSidebar: [{type: 'autogenerated', dirName: 'whelk'}],
  csSidebar: [{type: 'autogenerated', dirName: 'cs_base'}],
  mathSidebar: [{type: 'autogenerated', dirName: 'math'}],
};

module.exports = sidebars;
