name: Docker Build and Push

on:
  push:
    branches:
      - master  # Or the branch name you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/yiwen-blog-website:latest .

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/yiwen-blog-website:latest

    - name: Setup SSH Keys
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        ssh-add id_rsa

    - name: Deploy to Server via SSH
    run: |
      ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'ENDSSH'
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/yiwen-blog-website:latest
        docker stop yiwen-blog-website
        docker rm yiwen-blog-website
        docker run -d -p 8080:80 --name yiwen-blog-website ${{ secrets.DOCKER_HUB_USERNAME }}/yiwen-blog-website:latest
      ENDSSH
